apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflex-controller-manager
  namespace: kubeflex-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflex-controller-manager
  namespace: kubeflex-system
  labels:
    app.kubernetes.io/name: kubeflex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeflex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeflex
    spec:
      serviceAccountName: kubeflex-controller-manager
      containers:
      - name: manager
        image: ghcr.io/kubestellar/kubeflex/kubeflex-operator:v0.8.2
        command:
        - /manager
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
