apiVersion: v1
kind: Service
metadata:
  name: postgres-postgresql
  namespace: kubeflex-system
  labels:
    app.kubernetes.io/name: postgresql
spec:
  type: ClusterIP
  ports:
  - name: tcp-postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app.kubernetes.io/name: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-postgresql
  namespace: kubeflex-system
  labels:
    app.kubernetes.io/name: postgresql
spec:
  serviceName: postgres-postgresql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
    spec:
      containers:
      - name: postgresql
        image: docker.io/bitnami/postgresql:16.4.0
        env:
        - name: POSTGRESQL_USERNAME
          value: "postgres"
        - name: POSTGRESQL_PASSWORD
          value: "kubeflex"
        - name: POSTGRESQL_DATABASE
          value: "postgres"
        ports:
        - name: postgresql
          containerPort: 5432
