apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 10-core.yaml
- 20-rbac.yaml
- 21-cache-rbac.yaml
- 22-pod-policy.yaml
- 40-valkey.yaml
- 50-network.yaml
- crds/00-crds.yaml
