apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-controller
  namespace: argo
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-controller
  namespace: argo
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ''
  resources:
  - pods
  verbs: &id001
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs: &id002
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workflows/status
  - workflowtasksets
  - workflowtasksets/finalizers
  - workflowartifactgctasks
  verbs: *id001
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  - workflowtemplates/finalizers
  verbs: *id002
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - get
  - list
  - watch
  - deletecollection
- apiGroups:
  - argoproj.io
  resources:
  - cronworkflows
  - cronworkflows/status
  - cronworkflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-controller
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-controller
subjects:
- kind: ServiceAccount
  name: workflow-controller
  namespace: argo
