apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 10-controller.yaml
- 10-rbac.yaml
- 20-executor-rbac.yaml
- 40-result.yaml
- 50-network.yaml
- crds/clusterworkflowtemplates.argoproj.io.yaml
- crds/cronworkflows.argoproj.io.yaml
- crds/workflowartifactgctasks.argoproj.io.yaml
- crds/workfloweventbindings.argoproj.io.yaml
- crds/workflows.argoproj.io.yaml
- crds/workflowtaskresults.argoproj.io.yaml
- crds/workflowtasksets.argoproj.io.yaml
- crds/workflowtemplates.argoproj.io.yaml
