# Seed Bluefin k0s declarative stacks into /var/lib/k0s/manifests/
d /var/lib/k0s/manifests 0755 root root - -
C+ /var/lib/k0s/manifests/argocd - - - - /usr/share/k0s/manifests/argocd
C+ /var/lib/k0s/manifests/kubestellar - - - - /usr/share/k0s/manifests/kubestellar
C+ /var/lib/k0s/kiosk - - - - /usr/share/k0s/kiosk
