# Seed Bluefin k0s declarative stacks into /var/lib/k0s/manifests/
d /var/lib/k0s/manifests 0755 root root - -
d /etc/k0s 0755 root root - -
C+ /etc/k0s/k0s.yaml - - - - /usr/share/k0s/k0s.yaml
C+ /var/lib/k0s/manifests/argocd - - - - /usr/share/k0s/manifests/argocd
C+ /var/lib/k0s/manifests/kubestellar - - - - /usr/share/k0s/manifests/kubestellar
C+ /var/lib/k0s/kiosk - - - - /usr/share/k0s/kiosk
