apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 10-rbac.yaml
- 20-config.yaml
- 30-agent.yaml
- 40-operator.yaml
- 50-api-policies.yaml
- 51-platform-admission.yaml
- crds/00-crds.yaml
