#!/usr/bin/env python3
"""Render the homelab sysext's vendored Kubernetes manifests (offline step).

Every component below is pinned to one upstream chart or manifest version and
its sha256. This script downloads them, renders the charts with a pinned Helm
in a pinned container, rewrites every container image reference to
``tag@sha256:<index digest>`` (resolved with a pinned skopeo container) and
writes plain YAML to ``files/homelab/manifests/<NN-component>/``:

  00-crds.yaml        CustomResourceDefinitions (the applier waits for them
                      to be Established)
  01-namespace.yaml   the component's Namespace(s)
  10-<component>.yaml everything else the chart or manifest renders

Hand-written files in the same directories (``20-*.yaml``: the MetalLB pool,
issuers, the default Gateway, ...) are kept; only their image references are
pinned. Generated files start with GENERATED and are replaced on every run.

Site-specific values are ``${HOMELAB_*}`` placeholders that
/usr/libexec/bluefin-homelab-apply fills in from /etc/bluefin/homelab.conf.

The BuildStream build never runs this; it stages the committed YAML. Run it
after changing a pin (needs network and podman):

    python3 scripts/render-homelab-manifests.py
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "files" / "homelab" / "manifests"
ADDONS = ROOT / "files" / "homelab" / "addons"
HELM_IMAGE = "docker.io/alpine/helm:4.3.0@sha256:a6cf54599ccb99d90cf0712b30f03fdb3cab062e6b94e0418cc4db7e8a1464b2"
SKOPEO_IMAGE = "quay.io/skopeo/stable:v1.22.3@sha256:8482f709108354691af2defec4cad5f3ddea6cfff0c8091109dec8034574a918"
# Capabilities.KubeVersion for the charts: the kubeadm sysext's Kubernetes.
KUBE_VERSION = re.search(
    r'kubernetes-version: "([^"]+)"', (ROOT / "include" / "kubeadm.yml").read_text()
).group(1)
GENERATED = "# GENERATED by scripts/render-homelab-manifests.py; do not edit.\n"

# Kinds without a namespace; CRDs in the rendered output add their own.
CLUSTER_KINDS = {
    "APIService", "CSIDriver", "ClusterRole", "ClusterRoleBinding",
    "CustomResourceDefinition", "IngressClass", "MutatingWebhookConfiguration",
    "Namespace", "PersistentVolume", "PriorityClass", "RuntimeClass",
    "StorageClass", "ValidatingAdmissionPolicy", "ValidatingAdmissionPolicyBinding",
    "ValidatingWebhookConfiguration", "VolumeSnapshotClass",
}
REGISTRIES = r"(?:docker\.io|quay\.io|ghcr\.io|registry\.k8s\.io|nvcr\.io|gcr\.io|public\.ecr\.aws|mirror\.gcr\.io|cgr\.dev)"
# An image reference embedded in a longer string (args, embedded config).
EMBEDDED_IMAGE = re.compile(
    r"(?<![\w./@-])(" + REGISTRIES + r"/[a-z0-9._/-]+:[A-Za-z0-9._-]+)(@sha256:[0-9a-f]{64})?"
)


@dataclass
class Chart:
    repo: str  # https index URL or oci:// reference without the chart name
    name: str
    version: str
    sha256: str


@dataclass
class Manifest:
    url: str
    sha256: str


@dataclass
class Component:
    directory: str
    namespace: str
    source: Chart | Manifest
    release: str = ""
    values: dict = field(default_factory=dict)
    # The base set (OUT) or an add-on (ADDONS).
    root: Path = OUT


PH = lambda name: "${HOMELAB_" + name + "}"  # noqa: E731

COMPONENTS = [
    Component(
        "10-cilium", "kube-system",
        Chart("https://helm.cilium.io/", "cilium", "1.20.2",
              "b2afd87b7f75f875f92a14559f14f59b7babbb479d968e3fd625a20bf30ec20e"),
        release="cilium",
        values={
            "kubeProxyReplacement": True,
            # The API server address, read from the kubeconfig at apply time:
            # without kube-proxy, Cilium cannot reach it through the Service.
            "k8sServiceHost": PH("K8S_SERVICE_HOST"),
            "k8sServicePort": PH("K8S_SERVICE_PORT"),
            "routingMode": "tunnel",
            "tunnelProtocol": "vxlan",
            # Cilium's default pool is 10.0.0.0/8, which overlaps many home
            # LANs; use the conventional kubeadm/k0s pod CIDR.
            "ipam": {"mode": "cluster-pool", "operator": {"clusterPoolIPv4PodCIDRList": ["10.244.0.0/16"]}},
            "operator": {"replicas": 1},
            # Hubble certificates are generated in-cluster (no key material here).
            "hubble": {"relay": {"enabled": True}, "ui": {"enabled": False},
                       "tls": {"auto": {"method": "cronJob"}}},
        },
    ),
    Component(
        "20-local-path-provisioner", "local-path-storage",
        Manifest("https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.37/deploy/local-path-storage.yaml",
                 "9781b39c24f3f651bd6d6e41b561e04e4904bbdb6d4f8c7a6009df3a702dcd65"),
    ),
    Component(
        "21-nfs", "nfs-provisioner",
        Chart("https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/", "nfs-subdir-external-provisioner",
              "4.0.18", "a842163c1f5eedc4893e1f685e4249b0ddd62533c3c941228ee6a096ac308f6f"),
        release="nfs-subdir-external-provisioner",
        values={"nfs": {"server": PH("NFS_SERVER"), "path": PH("NFS_PATH")},
                "storageClass": {"name": "nfs-client", "defaultClass": False}},
    ),
    Component(
        "22-democratic-csi", "democratic-csi",
        Chart("https://democratic-csi.github.io/charts/", "democratic-csi", "0.15.1",
              "3d87e129cea46d49d810e9e5085b61d06c01a313bcf92160e3d106adc30426ed"),
        release="democratic-csi",
        values={
            "csiDriver": {"name": "org.democratic-csi.iscsi"},
            "storageClasses": [{
                "name": "democratic-csi-iscsi", "defaultClass": False, "reclaimPolicy": "Delete",
                "volumeBindingMode": "Immediate", "allowVolumeExpansion": True,
                "parameters": {"fsType": "ext4"}, "mountOptions": [],
                "secrets": {k: None for k in ("provisioner-secret", "controller-publish-secret",
                                              "node-stage-secret", "node-publish-secret",
                                              "controller-expand-secret")},
            }],
            "volumeSnapshotClasses": [],
            # The chart defaults to the moving "latest" tag.
            "controller": {"externalSnapshotter": {"enabled": False},
                           "driver": {"image": {"tag": "v1.9.5"}}},
            # The operator's driver config (NAS host, SSH key, portal,
            # dataset) becomes this Secret on the node; see the "secrets" file.
            "driver": {"existingConfigSecret": "democratic-csi-driver-config",
                       "config": {"driver": "zfs-generic-iscsi"}},
            "node": {"hostNetwork": True, "hostIPC": True,
                     "driver": {"image": {"tag": "v1.9.5"}, "localtimeHostPath": False, "iscsiDirHostPath": "/etc/iscsi",
                                "iscsiDirHostPathType": "DirectoryOrCreate"}},
        },
    ),
    Component(
        "30-metallb", "metallb-system",
        Chart("https://metallb.github.io/metallb", "metallb", "0.16.1",
              "fb06bb584fcb7856f15733b2a6a2aff5b61b5c350687e341c163ae24a5938adc"),
        release="metallb",
        # L2 mode only: neither the FRR sidecar nor the frr-k8s BGP backend.
        values={"speaker": {"frr": {"enabled": False}}, "frrk8s": {"enabled": False}},
    ),
    Component(
        "40-envoy-gateway", "envoy-gateway-system",
        Chart("oci://docker.io/envoyproxy", "gateway-helm", "v1.9.2",
              "1079cad009e0885f6e10e5f712257d8e5fdaf911d2ceb3fa1b78632c8f29bbf9"),
        release="eg",
        values={"deployment": {"replicas": 1},
                # The data-plane default built into Envoy Gateway v1.9.2
                # (api/v1alpha1/shared_types.go DefaultEnvoyProxyImage).
                "global": {"images": {"envoyProxy": {"image": "docker.io/envoyproxy/envoy:distroless-v1.39.1@sha256:eb2c01c13125d1629637cb4e4cce7207009fb7cc2c8027f9742758549d15b6f4"}}}},
    ),
    Component(
        "45-cert-manager", "cert-manager",
        Chart("https://charts.jetstack.io", "cert-manager", "v1.21.2",
              "73a56e1728edd6c99f1f31082618c3259d279a76b7ebd3d4bdc5475c2442d34a"),
        release="cert-manager",
        values={"crds": {"enabled": True}, "prometheus": {"enabled": False},
                "webhook": {"timeoutSeconds": 4},
                "config": {"apiVersion": "controller.config.cert-manager.io/v1alpha1",
                           "kind": "ControllerConfiguration", "gatewayAPI": {"enabled": True}}},
    ),
    Component(
        "50-argocd", "argocd",
        Manifest("https://raw.githubusercontent.com/argoproj/argo-cd/v3.5.3/manifests/install.yaml",
                 "7efe2d6bbc03f63623640f1e4198f16c84009d510fb810ef71e56df1b7614ba9"),
    ),
    Component(
        "60-metrics-server", "kube-system",
        Chart("https://kubernetes-sigs.github.io/metrics-server", "metrics-server", "3.14.0",
              "c2ca1185c01e6e7f53dd1b7d131f0c9b3fa50e003ed068b784563a1b5a3422a1"),
        release="metrics-server",
        values={"args": ["--kubelet-insecure-tls"]},
    ),
    Component(
        "61-reloader", "reloader",
        Chart("https://stakater.github.io/stakater-charts", "reloader", "2.2.18",
              "5eb4576ba75a0e165897e8a98a6ffef15d68939430da6eb8fe80796bba75cb17"),
        release="reloader",
        values={"reloader": {"reloadStrategy": "annotations",
                             "deployment": {"resources": {"requests": {"cpu": "10m", "memory": "64Mi"},
                                                          "limits": {"memory": "128Mi"}}}}},
    ),
    Component(
        "62-kured", "kube-system",
        Chart("https://kubereboot.github.io/charts", "kured", "6.1.0",
              "9451342cd13283a626fa63671eb593e88f734a848bdc02f49d42fd1b4ac224db"),
        release="kured",
        values={"configuration": {
            # Bluefin Server flags pending updates here (ddi-installer.md "Updates").
            "rebootSentinel": "/run/reboot-required",
            "rebootCommand": "/usr/bin/systemctl reboot",
            "timeZone": PH("KURED_TIME_ZONE"),
            "startTime": PH("KURED_START_TIME"),
            "endTime": PH("KURED_END_TIME"),
            "rebootDays": [PH("KURED_REBOOT_DAYS")],
            "annotateNodes": True,
        }},
    ),
    Component(
        "70-kube-prometheus-stack", "monitoring",
        Chart("https://prometheus-community.github.io/helm-charts", "kube-prometheus-stack", "91.8.2",
              "dbd50ecc4b3c4a0231d8a7c766d4fd8690be4bf2230acb572849fae129797a23"),
        release="kube-prometheus-stack",
        values={
            # Control-plane components bind to localhost on kubeadm and k0s, and
            # Cilium replaces kube-proxy: scraping them only raises alerts.
            "kubeProxy": {"enabled": False},
            "kubeEtcd": {"enabled": False},
            "kubeControllerManager": {"enabled": False},
            "kubeScheduler": {"enabled": False},
            "grafana": {
                # Generated on the node at first apply (see the "secrets" file).
                "admin": {"existingSecret": "grafana-admin", "userKey": "admin-user",
                          "passwordKey": "admin-password"},
                "additionalDataSources": [{"name": "Loki", "type": "loki", "uid": "loki",
                                           "url": "http://loki-gateway.monitoring.svc",
                                           "access": "proxy"}],
            },
            "prometheus": {"prometheusSpec": {
                "retention": "10d",
                # Pick up every ServiceMonitor/PodMonitor/rule in the cluster.
                "serviceMonitorSelectorNilUsesHelmValues": False,
                "podMonitorSelectorNilUsesHelmValues": False,
                "ruleSelectorNilUsesHelmValues": False,
                "storageSpec": {"volumeClaimTemplate": {"spec": {
                    "accessModes": ["ReadWriteOnce"],
                    "resources": {"requests": {"storage": "20Gi"}}}}},
            }},
        },
    ),
    Component(
        "71-loki", "monitoring",
        Chart("https://grafana-community.github.io/helm-charts", "loki", "18.13.7",
              "3cf98e0b8c4359be5095a6036c877a207be0d2cd10088cce83619d0f1663502b"),
        release="loki",
        values={
            "deploymentMode": "Monolithic",
            "loki": {
                "auth_enabled": False,
                "commonConfig": {"replication_factor": 1},
                "storage": {"type": "filesystem",
                            "bucketNames": {"chunks": "loki-chunks", "ruler": "loki-ruler", "admin": "loki-admin"}},
                "schemaConfig": {"configs": [{"from": "2024-04-01", "store": "tsdb", "object_store": "filesystem",
                                              "schema": "v13", "index": {"prefix": "loki_index_", "period": "24h"}}]},
                "limits_config": {"allow_structured_metadata": True, "volume_enabled": True,
                                  "retention_period": "336h"},
                "compactor": {"retention_enabled": True, "delete_request_store": "filesystem"},
                # One replica joins memberlist through its own headless Service
                # entry, which exists only once the pod is Ready; the chart's
                # abort-on-join-failure leaves the ingester shutting down.
                "extraMemberlistConfig": {"abort_if_cluster_join_fails": False,
                                          "min_join_backoff": "1s", "max_join_backoff": "1m",
                                          "max_join_retries": 10, "rejoin_interval": "90s"},
            },
            "singleBinary": {"replicas": 1, "persistence": {"enabled": True, "size": "20Gi"}},
            "backend": {"replicas": 0}, "read": {"replicas": 0}, "write": {"replicas": 0},
            "minio": {"enabled": False},
            "chunksCache": {"enabled": False}, "resultsCache": {"enabled": False},
            "gateway": {"enabled": True, "replicas": 1},
            "test": {"enabled": False}, "lokiCanary": {"enabled": False},
        },
    ),
    Component(
        "72-alloy", "monitoring",
        Chart("https://grafana.github.io/helm-charts", "alloy", "1.13.0",
              "bfdda6cb770c3526444897b9cb5a4fb33711c608d364d9e7857ec699a2fff4fb"),
        release="alloy",
        values={
            "controller": {"type": "daemonset", "tolerations": [{"operator": "Exists"}],
                           "volumes": {"extra": [
                               {"name": "machineid", "hostPath": {"path": "/etc/machine-id", "type": "File"}},
                               {"name": "alloy-data", "hostPath": {"path": "/var/lib/alloy", "type": "DirectoryOrCreate"}},
                           ]}},
            "alloy": {
                "storagePath": "/var/lib/alloy",
                "mounts": {"varlog": True, "extra": [
                    {"name": "machineid", "mountPath": "/etc/machine-id", "readOnly": True},
                    {"name": "alloy-data", "mountPath": "/var/lib/alloy"},
                ]},
                "securityContext": {"runAsUser": 0, "runAsGroup": 0, "allowPrivilegeEscalation": False,
                                    "capabilities": {"drop": ["ALL"]}},
                "configMap": {"content": (ROOT / "scripts" / "homelab-alloy.river").read_text()},
            },
            "crds": {"create": False},
        },
    ),
    Component(
        "80-gpu-operator", "gpu-operator",
        Chart("https://helm.ngc.nvidia.com/nvidia", "gpu-operator", "v26.7.1",
              "fdce4cba07db5ddb6dfd0bdf61276a44c24136f2b193bc6ebc81dd1b0f049777"),
        release="gpu-operator",
        values={
            # The nvidia-open-* and nvidia-container-toolkit sysexts provide the
            # driver and the CDI spec (nvidia-cdi-refresh); the device plugin
            # hands out CDI devices. The chart refuses the NRI plugin without
            # its own toolkit container ("the NRI Plugin cannot be enabled
            # when the Container Toolkit is disabled"), so it stays off.
            "driver": {"enabled": False},
            "toolkit": {"enabled": False},
            "cdi": {"enabled": True, "nriPluginEnabled": False},
            "dcgmExporter": {"serviceMonitor": {"enabled": False}},
        },
    ),
]


# The add-on sysexts' components: one directory each under ADDONS, applied
# after the base set in name order (files/homelab/addons/<NN-addon>/addon).
ADDON_COMPONENTS = [
    Component(
        "10-argo-workflows", "argo",
        # Namespace-scoped install; patch_argo_workflows sets the server's
        # auth mode and plain HTTP (TLS ends at the homelab Gateway).
        Manifest("https://github.com/argoproj/argo-workflows/releases/download/v4.1.4/namespace-install.yaml",
                 "947bbab7f9c99eb1e6b5ba47866afa531c1f485f3ad2586f6bfbc081a0057498"),
        root=ADDONS,
    ),
    Component(
        "20-mcp", "mcp",
        Chart("oci://ghcr.io/containers/charts", "kubernetes-mcp-server", "0.1.0",
              "2b9e0371b6a54ace8bfd9c100d61c766f0f8cec45de46040d28ea2e9f8c31484"),
        release="mcp",
        values={
            "image": {"registry": "quay.io", "repository": "containers/kubernetes_mcp_server", "version": "v0.0.67"},
            "ingress": {"enabled": False},
            # The server's own account gets no grant: every tool call runs
            # with the caller's bearer token (cluster_auth_mode passthrough).
            # Its token stays mounted: the in-cluster provider needs the
            # service account's CA and API server address.
            "rbac": {"create": False},
            # patch_mcp replaces the rendered config.toml with MCP_CONFIG.
            "config": {"port": "8080"},
        },
        root=ADDONS,
    ),
    Component(
        "30-kubestellar-console", "kubestellar-console",
        Chart("oci://ghcr.io/kubestellar/charts", "kubestellar-console", "0.3.42",
              "a6360659ba8e9c02380b34046f97af09d045a64e0e35d57168817d027b6a5609"),
        release="kubestellar-console",
        values={
            "image": {"tag": "v0.3.42"},
            # Secrets are generated on the node or read from the operator's
            # files (see the "secrets" file); no Secret in the chart. Without
            # a GitHub OAuth app (the optional Secret below) the Console's
            # /auth/github signs in as its built-in admin; 11-login-gate.yaml
            # puts that behind the Gateway's login password. Never DEV_MODE.
            "jwt": {"existingSecret": "kubestellar-console-jwt"},
            "auth": {"allowedGitHubLogins": PH("KUBESTELLAR_CONSOLE_ALLOWED_LOGINS"),
                     "adminGitHubLogins": PH("KUBESTELLAR_CONSOLE_ADMIN_LOGINS")},
            # A switch between GitHub and password sign-in rolls the pod.
            "podAnnotations": {"homelab.bluefin.dev/console-sign-in": PH("KUBESTELLAR_CONSOLE_SIGN_IN")},
            "persistence": {"enabled": True, "accessModes": ["ReadWriteOnce"]},
            "backup": {"enabled": False},
            "selfUpgrade": {"enabled": False},
            "rbac": {"resourceQuotasReadOnly": True},
            "extraEnv": [
                {"name": "FRONTEND_URL", "value": "https://kubestellar.${HOMELAB_DOMAIN}"},
                *({"name": f"GITHUB_CLIENT_{key.upper()}", "valueFrom": {"secretKeyRef": {
                    "name": "kubestellar-console-github-oauth", "key": f"github-client-{key}", "optional": True}}}
                  for key in ("id", "secret")),
                # Only the OAuth app above, never one a /auth/manifest/setup
                # flow stored in the database; that flow needs this token.
                {"name": "IGNORE_PERSISTED_OAUTH_CREDENTIALS", "value": "true"},
                {"name": "CONSOLE_BOOTSTRAP_TOKEN", "valueFrom": {"secretKeyRef": {
                    "name": "kubestellar-console-bootstrap", "key": "bootstrap-token"}}},
            ],
        },
        root=ADDONS,
    ),
    Component(
        # Full KubeStellar: KubeFlex and the KubeStellar PostCreateHooks
        # (controller manager, transport, status add-on) for the ITS/WDS
        # control planes one creates. KubeFlex's own Postgres is a Helm
        # install at runtime; 20-postgres.yaml replaces it (patch_kubestellar_full).
        "31-kubestellar-full", "kubeflex-system",
        Chart("oci://ghcr.io/kubestellar/kubestellar", "core-chart", "0.30.0",
              "a66697c077431c4e2cff73764f9b60fc15b3af75ad3e9e70ddda9c94d4c996ad"),
        release="ks",
        root=ADDONS,
    ),
]

# kubernetes-mcp-server's config: HTTP on 8080 (Streamable HTTP at /mcp),
# read-only unless homelab.conf says HOMELAB_MCP_READ_WRITE=yes, and every
# request must carry a bearer token, which the server forwards to the API
# server: Kubernetes authenticates and authorizes each call (the generated
# mcp-client token is bound to the "view" ClusterRole).
MCP_CONFIG = """port = "8080"
stateless = true
read_only = ${HOMELAB_MCP_READ_ONLY}
toolsets = ["core", "config"]
cluster_provider_strategy = "in-cluster"
require_oauth = true
skip_jwt_verification = true
cluster_auth_mode = "passthrough"

[[denied_resources]]
group = ""
version = "v1"
kind = "Secret"
"""


def patch_argo_workflows(docs: list[dict]) -> list[dict]:
    for d in docs:
        if d["kind"] == "Deployment" and d["metadata"]["name"] == "argo-server":
            c = d["spec"]["template"]["spec"]["containers"][0]
            # Clients authenticate with their own Kubernetes token
            # (kubectl create token), and the Gateway speaks plain HTTP.
            c["args"] += ["--auth-mode=client", "--secure=false"]
            c["readinessProbe"]["httpGet"]["scheme"] = "HTTP"
        if d["kind"] == "ConfigMap" and d["metadata"]["name"] == "workflow-controller-configmap":
            # The executor the controller injects into workflow pods,
            # pinned like every other image.
            d["data"] = {"executor": "image: quay.io/argoproj/argoexec:v4.1.4\n"}
        if d["kind"] in ("RoleBinding", "ClusterRoleBinding"):
            for s in d.get("subjects", []):
                if s["kind"] == "ServiceAccount":
                    s.setdefault("namespace", "argo")
    return docs


def patch_mcp(docs: list[dict]) -> list[dict]:
    for d in docs:
        if d["kind"] == "ConfigMap":
            d["data"] = {"config.toml": MCP_CONFIG}
        if d["kind"] == "Deployment":
            # The chart's config checksum is of its own config; reloader
            # restarts the pod when the applier changes read_only.
            tmpl = d["spec"]["template"]["metadata"]
            tmpl.get("annotations", {}).pop("checksum/config", None)
            if not tmpl.get("annotations"):
                tmpl.pop("annotations", None)
            d["metadata"].setdefault("annotations", {})["reloader.stakater.com/auto"] = "true"
    return docs


def patch_console(docs: list[dict]) -> list[dict]:
    for d in docs:
        if d["kind"] == "Deployment":
            # reloader restarts the pod when the operator's OAuth app changes.
            d["metadata"].setdefault("annotations", {})["reloader.stakater.com/auto"] = "true"
    # The chart's pre-upgrade PVC migration (a Helm hook for its own
    # upgrades) has no place in a plain apply.
    return [d for d in docs if not d["metadata"]["name"].startswith("kubestellar-console-pvc-migration")]


def patch_kubestellar_full(docs: list[dict]) -> list[dict]:
    return [d for d in docs if not (d["kind"] == "Job" and "install-postgresql" in d["metadata"]["name"])]


PATCHES = {
    "20-local-path-provisioner": lambda docs: patch_local_path(docs),
    "10-argo-workflows": patch_argo_workflows,
    "20-mcp": patch_mcp,
    "30-kubestellar-console": patch_console,
    "31-kubestellar-full": patch_kubestellar_full,
}


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    result = subprocess.run(cmd, text=True, **kw)
    if result.returncode:
        sys.exit(f"{' '.join(cmd)} failed:\n{result.stderr or ''}")
    return result


def podman(image: str, work: Path, args: list[str], entrypoint: str = "", **kw) -> subprocess.CompletedProcess:
    opts = ["--entrypoint", entrypoint] if entrypoint else []
    return run(["podman", "run", "--rm", "--dns=1.1.1.1", "--security-opt", "label=disable",
                "-v", f"{work}:/work", "-w", "/work", *opts, image, *args], **kw)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verify(path: Path, expected: str, what: str, pins_only: bool) -> None:
    actual = sha256(path)
    if pins_only:
        print(f"{what}: {actual}")
    elif actual != expected:
        sys.exit(f"{what}: sha256 {actual} does not match the pin {expected}")


def fetch(comp: Component, work: Path, pins_only: bool) -> Path:
    src = comp.source
    if isinstance(src, Manifest):
        dest = work / f"{comp.directory}.yaml"
        if not dest.exists():
            req = urllib.request.Request(src.url, headers={"User-Agent": "bluefin-render"})
            dest.write_bytes(urllib.request.urlopen(req, timeout=120).read())
        verify(dest, src.sha256, src.url, pins_only)
        return dest
    dest = work / "charts" / f"{src.name}-{src.version}.tgz"
    if not dest.exists():
        dest.parent.mkdir(parents=True, exist_ok=True)
        if src.repo.startswith("oci://"):
            pull = [f"{src.repo}/{src.name}"]
        else:
            pull = [src.name, "--repo", src.repo]
        podman(HELM_IMAGE, work, ["pull", *pull, "--version", src.version, "-d", "/work/charts"],
               stdout=subprocess.DEVNULL)
    verify(dest, src.sha256, f"{src.name} {src.version}", pins_only)
    return dest


def helm_template(comp: Component, chart: Path, work: Path) -> str:
    values = work / f"{comp.directory}.values.json"
    values.write_text(json.dumps(comp.values))
    args = ["template", comp.release, f"/work/{chart.relative_to(work)}",
            "--namespace", comp.namespace, "--include-crds", "--kube-version", KUBE_VERSION,
            "-f", f"/work/{values.name}"]
    out = podman(HELM_IMAGE, work, args, capture_output=True).stdout
    again = podman(HELM_IMAGE, work, args, capture_output=True).stdout
    if out != again:
        sys.exit(f"{comp.directory}: helm template is not deterministic (random values?)")
    return out


def walk_strings(node, fn):
    """Return node with fn(key, value) applied to every string value (key is
    None for list items)."""
    if isinstance(node, dict):
        return {k: (fn(k, v) if isinstance(v, str) else walk_strings(v, fn)) for k, v in node.items()}
    if isinstance(node, list):
        return [fn(None, v) if isinstance(v, str) else walk_strings(v, fn) for v in node]
    return node


def normalize(ref: str) -> str:
    first = ref.split("/", 1)[0]
    if "/" not in ref:
        ref = f"docker.io/library/{ref}"
    elif "." not in first and ":" not in first and first != "localhost":
        ref = f"docker.io/{ref}"
    if ":" not in ref.rsplit("/", 1)[-1] and "@" not in ref:
        sys.exit(f"image {ref} has no tag; pin a tag in the render script")
    return ref


class Digests:
    """tag -> index digest, resolved in one pinned skopeo container per batch."""

    def __init__(self, work: Path):
        self.cache_file = work / "digests.json"
        self.cache = json.loads(self.cache_file.read_text()) if self.cache_file.exists() else {}
        self.work = work

    def resolve(self, refs: set[str]) -> None:
        missing = sorted(r for r in refs if r not in self.cache)
        if not missing:
            return
        (self.work / "refs.txt").write_text("\n".join(missing) + "\n")
        script = ('while read -r r; do d=$(skopeo inspect --retry-times 3 --raw "docker://$r" | sha256sum); '
                  'echo "$r ${d%% *}"; done < /work/refs.txt')
        out = podman(SKOPEO_IMAGE, self.work, ["-c", script], entrypoint="sh", capture_output=True).stdout
        for line in out.splitlines():
            ref, digest = line.split()
            self.cache[ref] = f"sha256:{digest}"
        self.cache_file.write_text(json.dumps(self.cache, indent=1))
        unresolved = [r for r in missing if r not in self.cache]
        if unresolved:
            sys.exit(f"could not resolve {unresolved}")

    def pin(self, ref: str) -> str:
        return ref if "@sha256:" in ref else f"{ref}@{self.cache[ref]}"


def image_key(doc, key) -> bool:
    # A ClusterPolicy splits images into repository/image/version, handled
    # by nvidia_image_specs.
    return key == "image" and doc.get("kind") != "ClusterPolicy"


def image_refs(doc) -> set[str]:
    refs: set[str] = set()

    def collect(key, value):
        if image_key(doc, key) and value and "${" not in value and "@sha256:" not in value:
            refs.add(normalize(value))
        for m in EMBEDDED_IMAGE.finditer(value):
            if not m.group(2):
                refs.add(m.group(1))
        return value

    walk_strings(doc, collect)
    if doc.get("kind") == "ClusterPolicy":
        for spec in nvidia_image_specs(doc):
            refs.add(f"{spec['repository']}/{spec['image']}:{spec['version']}")
    return refs


def nvidia_image_specs(doc):
    """GPU Operator ClusterPolicy entries with repository/image/version keys."""
    stack = [doc.get("spec", {})]
    while stack:
        node = stack.pop()
        if isinstance(node, dict):
            if {"repository", "image", "version"} <= node.keys() and not str(node["version"]).startswith("sha256:"):
                yield node
            stack.extend(node.values())
        elif isinstance(node, list):
            stack.extend(node)


def pin_images(doc, digests: Digests):
    def rewrite(key, value):
        if image_key(doc, key) and value and "${" not in value and "@sha256:" not in value:
            return digests.pin(normalize(value))
        return EMBEDDED_IMAGE.sub(lambda m: m.group(0) if m.group(2) else digests.pin(m.group(1)), value)

    doc = walk_strings(doc, rewrite)
    if doc.get("kind") == "ClusterPolicy":
        for spec in nvidia_image_specs(doc):
            # The operator accepts a digest as the version.
            spec["version"] = digests.cache[f"{spec['repository']}/{spec['image']}:{spec['version']}"]
    return doc


HOOK_SKIP = {"test", "test-success", "test-failure", "pre-delete", "post-delete", "pre-rollback", "post-rollback"}


def postprocess(docs: list[dict], comp: Component) -> list[dict]:
    cluster_kinds = set(CLUSTER_KINDS)
    for d in docs:
        if d["kind"] == "CustomResourceDefinition" and d["spec"].get("scope") == "Cluster":
            cluster_kinds.add(d["spec"]["names"]["kind"])
    cluster_kinds |= {"ClusterIssuer", "GatewayClass", "ClusterPolicy", "NodeFeatureRule"}
    out = []
    for d in docs:
        meta = d.setdefault("metadata", {})
        ann = meta.get("annotations") or {}
        hooks = {h.strip() for h in ann.get("helm.sh/hook", "").split(",") if h.strip()}
        if hooks & HOOK_SKIP and not hooks - HOOK_SKIP:
            continue
        for key in [k for k in ann if k.startswith("helm.sh/hook")]:
            del ann[key]
        if not ann:
            meta.pop("annotations", None)
        if d["kind"] not in cluster_kinds and not meta.get("namespace"):
            meta["namespace"] = comp.namespace
        if d["kind"] == "Job":
            # Jobs are immutable: a new pin gets a new Job, the old one stays.
            spec = json.dumps(d["spec"], sort_keys=True).encode()
            meta["name"] = f"{meta['name'][:54]}-{hashlib.sha256(spec).hexdigest()[:8]}"
        for wh in d.get("webhooks", []) if d["kind"].endswith("WebhookConfiguration") else []:
            # Injected at runtime (cert-manager cainjector, certgen jobs); an
            # empty value in the manifest would reset it on every apply.
            if not wh.get("clientConfig", {}).get("caBundle"):
                wh.get("clientConfig", {}).pop("caBundle", None)
        if d["kind"] == "CustomResourceDefinition":
            conv = d["spec"].get("conversion", {}).get("webhook", {}).get("clientConfig", {})
            if "caBundle" in conv and not conv["caBundle"]:
                del conv["caBundle"]
        out.append(d)
    return out


def patch_local_path(docs: list[dict]) -> list[dict]:
    for d in docs:
        if d["kind"] == "ConfigMap" and d["metadata"]["name"] == "local-path-config":
            cfg = json.loads(d["data"]["config.json"])
            for node in cfg["nodePathMap"]:
                # /opt is a plain host directory kept for CNI binaries; /var
                # is the node's persistent state.
                node["paths"] = ["/var/lib/local-path-provisioner"]
            d["data"]["config.json"] = json.dumps(cfg, indent=2) + "\n"
            d["data"]["helperPod.yaml"] = d["data"]["helperPod.yaml"].replace(
                "image: docker.io/library/busybox\n", "image: docker.io/library/busybox:1.37.0\n")
        if d["kind"] == "StorageClass":
            d["metadata"].setdefault("annotations", {})["storageclass.kubernetes.io/is-default-class"] = "true"
    return docs


class Dumper(yaml.SafeDumper):
    pass


def _str(dumper, value):
    if "${HOMELAB_" in value and "\n" not in value:
        # Stays a string whatever the applier substitutes (a port, a name).
        return dumper.represent_scalar("tag:yaml.org,2002:str", value, style='"')
    if "\n" in value and not any(line != line.rstrip() for line in value.splitlines()):
        return dumper.represent_scalar("tag:yaml.org,2002:str", value, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", value)


Dumper.add_representer(str, _str)


def dump(path: Path, docs: list[dict]) -> None:
    body = "---\n".join(yaml.dump(d, Dumper=Dumper, sort_keys=False, width=1 << 16) for d in docs)
    path.write_text(GENERATED + "---\n" + body)


def write_component(comp: Component, docs: list[dict]) -> None:
    out = comp.root / comp.directory
    out.mkdir(parents=True, exist_ok=True)
    for f in out.glob("*.yaml"):
        if f.read_text().startswith(GENERATED):
            f.unlink()
    crds = [d for d in docs if d["kind"] == "CustomResourceDefinition"]
    namespaces = [d for d in docs if d["kind"] == "Namespace"]
    if comp.namespace not in ("kube-system", "default") and comp.namespace not in [
        n["metadata"]["name"] for n in namespaces
    ]:
        namespaces.insert(0, {"apiVersion": "v1", "kind": "Namespace", "metadata": {"name": comp.namespace}})
    rest = [d for d in docs if d["kind"] not in ("CustomResourceDefinition", "Namespace")]
    if crds:
        dump(out / "00-crds.yaml", crds)
    if namespaces:
        dump(out / "01-namespace.yaml", namespaces)
    dump(out / f"10-{comp.directory.split('-', 1)[1]}.yaml", rest)


class Loader(yaml.SafeLoader):
    pass


# PyYAML resolves a bare "=" (YAML 1.1 value key) to a tag it cannot construct.
Loader.add_constructor("tag:yaml.org,2002:value", lambda loader, node: loader.construct_scalar(node))


def load(text: str) -> list[dict]:
    return [d for d in yaml.load_all(text, Loader=Loader) if d]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--work", type=Path, default=Path("/var/tmp/bluefin-homelab-render"),
                        help="scratch directory (charts, digest cache)")
    parser.add_argument("--print-pins", action="store_true",
                        help="download every source and print its sha256 instead of rendering")
    parser.add_argument("--only", help="render only this component directory")
    args = parser.parse_args()
    work = args.work.resolve()
    work.mkdir(parents=True, exist_ok=True)
    selected = [c for c in COMPONENTS + ADDON_COMPONENTS if not args.only or c.directory == args.only]

    rendered = {}
    for comp in selected:
        src = fetch(comp, work, args.print_pins)
        if args.print_pins:
            continue
        if isinstance(comp.source, Manifest):
            docs = load(src.read_text())
        else:
            docs = load(helm_template(comp, src, work))
        docs = postprocess(docs, comp)
        rendered[comp.directory] = PATCHES.get(comp.directory, lambda d: d)(docs)
    if args.print_pins:
        return

    hand_written = {f: load(f.read_text()) for f in sorted([*OUT.glob("*/*.yaml"), *ADDONS.glob("*/*.yaml")])
                    if not f.read_text().startswith(GENERATED)}
    digests = Digests(work)
    refs: set[str] = set()
    for docs in [*rendered.values(), *hand_written.values()]:
        for d in docs:
            refs |= image_refs(d)
    digests.resolve(refs)

    for comp in selected:
        write_component(comp, [pin_images(d, digests) for d in rendered[comp.directory]])
    for path, docs in hand_written.items():
        pinned = [pin_images(d, digests) for d in docs]
        if pinned != docs:
            sys.exit(f"{path.relative_to(ROOT)}: pin its images by digest by hand "
                     f"({sorted(r for d in docs for r in image_refs(d))})")

    for root in (OUT, ADDONS):
        total = sum(f.stat().st_size for f in root.rglob("*") if f.is_file())
        print(f"wrote {root.relative_to(ROOT)}: {total} bytes")


if __name__ == "__main__":
    main()
